deliver(
force = true
# baseLanguage = "en-Au"
app_identifier = "com.stonedcrone.WingIt"
app = 1292454564
skip_binary_upload = true
build_number = "${XCODE_BUILD_NUMBER}"
submit_for_review = true
automatic_release = true
team_name = "Eli Labes"
metadata_path: "./metadata"
submission_information({
    add_id_info_serves_ads: false,
    add_id_info_uses_idfa: false,
    add_id_info_tracks_install: false,
    add_id_info_tracks_action: false,
    add_id_info_limits_tracking: false,
    content_rights_has_rights: false,
    content_rights_contains_third_party_content: false,
    export_compliance_contains_third_party_cryptography: false,
    export_compliance_encryption_updated: false,
    export_compliance_platform: 'ios',
    export_compliance_compliance_required: false,
    export_compliance_uses_encryption: false,
    export_compliance_is_exempt: false,
    export_compliance_contains_proprietary_cryptography: false,
    export_compliance_available_on_french_store: false
})
